server:
  port: 8081
  servlet:
    contextPath: /api

spring:
  application:
    name: customer

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    username: root
    password: Mcgonagall1999


  security:
    user:
      name: bong
      password: password
      roles: admin